MODULE Main;
REQUIRE EvalScript, Currency, Static;

showMessage() {
   MESSAGE 'Hello World Ernad Husremović!';
}

FORM formHelloWorld 'Forma1'
    PROPERTIES 'Polje1  :' = 'Hello world!';
;


openFile() {
   INPUT f = EXCELFILE DO {
      
   }
}

NAVIGATOR {
   NEW FOLDER hello 'Hello' WINDOW toolbar {
      NEW ACTION showMessage;
      NEW FORM formHelloWorld;
      NEW FORM directions;
      NEW ACTION openFile;
   }
}



